server:
  port: 8808
spring:
  datasource:
    url: jdbc:mysql://rm-bp11ge447re5j03792o.mysql.rds.aliyuncs.com:3306/my_test?useUnicode=true&characterEncoding=utf-8
    username: "starshine_test"
    password: "Chenlu19941204"
    initialSize: 1
    minIdle: 1
    maxActive: 2
mybatis:
  mapper-locations: classpath:mapper/*.xml